Repository Projeto-Satisfacao/Projeto_Satisfacao, pull requests merged in 2023-04, with the labels that each got.

#3 Banco_de_dados
  ModelConexao.class.php
  ModelUser.class.php
Labels: banco-de-dados

#8 Tela de satisfacao
  satifacao/agradecimento.html
  satifacao/bootstrap.bundle.min.js
  satifacao/bootstrap.bundle.min.js.map
  satifacao/bootstrap.min.css
  satifacao/bootstrap.min.css.map
  satifacao/imagens/10042709.png
  satifacao/imagens/bom (2).png
  satifacao/imagens/bom.png
  satifacao/imagens/excelente (2).png
  satifacao/imagens/excelente.png
  satifacao/imagens/logo senai.png
  satifacao/imagens/neutro.png
  satifacao/imagens/pessimo (2).png
  satifacao/imagens/pessimo.png
  satifacao/imagens/regular.png
  satifacao/imagens/ruim.png
  satifacao/imagens/ruimm.png
  satifacao/imagens/senai.jpg
  satifacao/index.html
  satifacao/index.js
  satifacao/jquery-3.6.4.min.js
  satifacao/style.css
  satifacao/styleAgradecimento.css
Labels: front-end

#16 View-Creats
  view/DepartmentFormView.php
  view/DepartmentListView.php
  view/LocalFormView.php
  view/LocalListView.php
  view/LoginFormView.php
  view/SurveyFormView.php
  view/SurveyListView.php
  view/UserFormView.php
  view/UserListView.php
Labels: back-end

#23 tela-avaliacao-atualizada
  telas-front/index-avaliacao.html
Labels: front-end

#24 Atualização-tratamento-erros
  app/controller/DepartmentController.php
  app/controller/LocalController.php
  app/controller/SurveyController.php
  app/controller/UserController.php
  app/model/DepartmentModel.php
  app/model/LocalModel.php
  app/model/SurveyModel.php
  app/model/UserModel.php
  app/view/LocalFormView.php
  app/view/UserFormView.php
Labels: back-end

#29 APP atualização de tratamento de erros
  app/controller/DepartmentController.php
  app/controller/LocalController.php
  app/controller/SurveyController.php
  app/controller/UserController.php
  app/model/DepartmentModel.php
  app/model/UserModel.php
  testes/TesteDepartment.php
  testes/TesteLocal.php
  testes/TesteSurvey.php
Labels: back-end, banco-de-dados

#47 Realizando fetch para salvar avaliacao no banco
  action_page.php
  app/model/SurveyModel.php
  app/view/SurveyFormView.php
  assets/js/avaliacao/audioAvaliacao.js
  assets/js/avaliacao/fetchAvaliacao.js
  pages/index-avaliacao.html
Labels: back-end

#48 Salvando avaliações no banco de acordo com o departamento associado
  action_page.php
  app/model/SurveyModel.php
  app/view/DepartmentFormView.php
  app/view/LocalFormView.php
  app/view/SurveyFormView.php
  app/view/UserFormView.php
  assets/js/avaliacao/associarDepartment.js
  assets/js/avaliacao/fetchAvaliacao.js
  core/Database.php
  pages/index-list-setores-locais.php
Labels: back-end

#54 Adicionando scores do banco ao dashboard
  action_page.php
  app/Controller/DepartmentController.php
  app/Controller/SurveyController.php
  app/Model/SurveyModel.php
  assets/js/dashboards/dashboards.js
  assets/js/dashboards/fetchSelect.js
  pages/index-dashboard.php
Labels: front-end, back-end

#56 add popup no index-cadastro
  action_page.php
  pages/index-cadastros.php
Labels: front-end
